env: # Environment variables to pass to all tasks
    CIRRUS_CLONE_DEPTH: 1 # No need to clone with the whole history
    CIRRUS_WORKING_DIR: "/tmp"

# store our secrets here
    NGROK_TOKEN: "ENCRYPTED[88039e31e7dacf1a75d8f6f0cb38fd0f5ffe7986ea7583438e6d32986ab7c6a1ebbbe2b531ef6ea694094016b8b21413]"
    NGROK_REGION: US
    SSH_PASSWORD: "ENCRYPTED[69020a5f73473b6c93b9d4b1ad40813af251049a66e27fe8d272d6b240abe520336948efa8b21b55c8d0497b15ce2fc7]"
    TELEGRAM_BOT_TOKEN: "ENCRYPTED[b3eadd5d31b2ffe5ae5e94c3eb8f11bad6b073696930eccd1d4a6fa191faab55be94823d6bd3df8dac73ae9b5e07c530]"
    TELEGRAM_CHAT_ID: "ENCRYPTED[a0802814ae4b40b2245ddc94f75b63085b821f486a22dc02f8dbe06d8c52852c5ceed339e9722fba89a9fd1cef9e9ec2]"

task:
    name: ssh
    timeout_in: 260m
    container:
      image: ubuntu:latest
      cpu: 8
      memory: 32G
    down: # To download ccache in background
      - mkdir -p ~/.ssh
      - cat << EOF > ~/.ssh/config
      - Host *
      -     ServerAliveInterval 60
      -     StrictHostKeyChecking no
      - Host cirrus-ci.com
      -     User cirrus 
      -     Port 22
      -     Hostname cirrus-ci.com
      -     TCPKeepAlive yes
      -     IdentitiesOnly yes
      - EOF      


    sync_script:
      - bash ngrok2actions
